# Generated by Django 4.2.7 on 2023-12-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(help_text='Enter brand name', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter brand name again in lowercasse', max_length=100, null=True, unique=True),
        ),
    ]
