# Generated by Django 4.2.7 on 2023-12-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_brand_name_alter_brand_slug'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/media/uploads/'),
        ),
        migrations.RemoveField(
            model_name='postcar',
            name='brand',
        ),
        migrations.AddField(
            model_name='postcar',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
    ]
