# Generated by Django 4.2.7 on 2023-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_postcar_quantity_available_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
