# Generated by Django 4.2.7 on 2023-12-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_purchase_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='qty',
        ),
    ]
